import http from 'k6/http';
import { check, sleep } from 'k6';
import { Trend } from 'k6/metrics';

// Stress test for the Oscar API (nominees endpoints).
// Run with:
//   k6 run k6/stress-test.js
// Override target host or stages via env vars:
//   k6 run -e BASE_URL=http://localhost:3000 k6/stress-test.js

const BASE_URL = __ENV.BASE_URL || 'http://localhost:3031';

const createLatency = new Trend('nominee_create_duration');
const listLatency = new Trend('nominee_list_duration');
const getLatency = new Trend('nominee_get_duration');
const updateLatency = new Trend('nominee_update_duration');

export const options = {
  scenarios: {
    stress: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: '30s', target: 20 }, // warm up
        { duration: '1m', target: 50 }, // ramp to normal-ish load
        { duration: '1m', target: 150 }, // push past normal load
        { duration: '1m', target: 300 }, // stress
        { duration: '30s', target: 0 }, // recovery
      ],
      gracefulRampDown: '10s',
    },
  },
  thresholds: {
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<1000'],
  },
};

function randomTitle() {
  return `Stress Test Nominee ${Date.now()}-${Math.floor(Math.random() * 100000)}`;
}

function createNomineePayload() {
  return JSON.stringify({
    title: randomTitle(),
    description: 'Nominee generated by k6 stress test',
    release: 2000 + Math.floor(Math.random() * 25),
    director: 'k6 Load Director',
    winner: Math.random() < 0.5,
  });
}

const jsonHeaders = { headers: { 'Content-Type': 'application/json' } };

export default function () {
  // Health check
  const ping = http.get(`${BASE_URL}/ping`);
  check(ping, { 'ping status is 200': (r) => r.status === 200 });

  // List with pagination + filter + sort
  const page = Math.floor(Math.random() * 5) + 1;
  const listRes = http.get(
    `${BASE_URL}/nominees?page=${page}&limit=10&sortBy=title&sortOrder=asc`,
  );
  listLatency.add(listRes.timings.duration);
  check(listRes, {
    'list status is 200': (r) => r.status === 200,
  });

  // Create a nominee
  const createRes = http.post(
    `${BASE_URL}/nominees`,
    createNomineePayload(),
    jsonHeaders,
  );
  createLatency.add(createRes.timings.duration);
  const created = check(createRes, {
    'create status is 201': (r) => r.status === 201,
  });

  if (created) {
    let body;
    try {
      body = JSON.parse(createRes.body);
    } catch (e) {
      body = null;
    }
    const id = body && (body._id || body.id);

    if (id) {
      // Fetch the created nominee
      const getRes = http.get(`${BASE_URL}/nominees/${id}`);
      getLatency.add(getRes.timings.duration);
      check(getRes, { 'get status is 200': (r) => r.status === 200 });

      // Update it
      const updateRes = http.put(
        `${BASE_URL}/nominees/${id}`,
        JSON.stringify({ winner: true }),
        jsonHeaders,
      );
      updateLatency.add(updateRes.timings.duration);
      check(updateRes, {
        'update status is 200 or 201': (r) =>
          r.status === 200 || r.status === 201,
      });
    }
  }

  sleep(1);
}
